TRAIN:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 256
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: memcache_manifold://fair_vision_data/tree/imagenet_full_size
  PATH_TO_PRELOAD_IMDB: manifold://fair_vision_data/tree/imagenet_full_size
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  NUM_FRAMES: 1
  # SAMPLING_RATE: 8
  # TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
MVIT:
  MODE: "max"
  CLS_EMBED_ON: True
  PATCH_KERNEL: (1, 7, 7)
  PATCH_STRIDE: (1, 4, 4)
  PATCH_PADDING: (0, 3, 3)
  EMBED_DIM: 96
  NUM_HEADS: 1
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.1
  DEPTH: 16
  NORM: "layernorm"
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KV_KERNEL: [[1, 5, 5], [1, 3, 3], [1, 3, 3], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]  # kxy4t2
  # POOL_KV_KERNEL: [[1, 5, 5], [1, 3, 3], [1, 3, 3], [], [], [], [], [], [], [], [], [], [], [], [], []]  # kxy4t2
  POOL_Q_KERNEL: [[], [1, 3, 3], [], [1, 3, 3], [], [], [], [], [], [], [], [], [], [], [1, 2, 2], []]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0005
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000001
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-5
  ZERO_WD_1D_PARAM: True
MODEL:
  NUM_CLASSES: 1000
  ARCH: 2d
  MODEL_NAME: MViT
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 256
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
